import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="flex h-full">
					<div className="hide-scrollbar flex w-14 flex-col justify-between p-2 overflow-y-auto border-r bg-studio border-default">
						<ul className="flex flex-col space-y-2">
							<a className="block" href="/dashboard/projects">
								<Image
									src="/logo.svg"
									alt="ssm"
									className="mx-auto h-[40px] w-6 cursor-pointer rounded"
									width={24}
									height={40}
								/>
							</a>

							<button data-state="closed">
								<a href="/">
									<span className="transition-colors duration-200 flex items-center justify-center h-10 w-10 rounded text-foreground-lighter hover:text-foreground  bg-studio hover:bg-surface-200 !bg-surface-300 !text-foreground shadow-sm">
										<svg
											xmlns="http://www.w3.org/2000/svg"
											width="18"
											height="18"
											viewBox="0 0 24 24"
											fill="none"
											stroke="currentColor"
											stroke-width="2"
											stroke-linecap="round"
											stroke-linejoin="round"
											className="sbui-icon"
										>
											<path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path>
											<polyline points="9 22 9 12 15 12 15 22"></polyline>
										</svg>
									</span>
								</a>
							</button>
						</ul>
					</div>
					<main
						className="flex-1 overflow-y-auto"
						style={{ maxHeight: "100vh" }}
					>
						{children}
					</main>
				</div>
			</body>
		</html>
	);
}
