import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Layout } from "@/components/core/layout";

import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className + " dark"}>
				<Layout.Container>
					<Layout.Menu />
					<Layout.Main>{children}</Layout.Main>
				</Layout.Container>
			</body>
		</html>
	);
}
